services:
  sis-colegios:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    container_name: sis-colegios
    restart: unless-stopped
    ports:
      - "8096:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
